### ISSUE TITLE
How did you generate the ground-truth for your test image

### ISSUE THREAD

**Issue by hujinhan12** [elliottwu/DeepHDR#10] opened 2019-09-24 22:04 UTC
Hi,
I just have one question.
When I am trying to test the network with some random captures, I don't know how to create the correct ground-truth for 3 static images I captured.
I simply used the triangle method in Kalatari's work, but my output is probably different from yours.
If I just read ref_hdr_aligned.hdr and convert it to png using gamma = 2.2, the output image looks very dark.
Can you share with me how you created the ground-truth for the test data you captured?
Thanks a lot.

**Comment by elliottwu** [comment] 2019-09-26 00:11
We directly used the HDR images provided in Kalantari's dataset, and didn't create our own by actually fusing the static shots. 
Inverse gamma function is only an approximation for tonemapping. The output can appear dull (dim and bleached). To check if you have obtained a "correct" HDR, you may use more powerful tonemapping functions, such as the ones provided in Photomatix.

**Comment by elliottwu** [comment] 2019-09-26 00:16
Duplicate of #6

**Comment by elliottwu** [comment] 2019-09-26 00:17
Duplicate of #5

**Closed** 2019-10-02 12:22 UTC
